config/routes.rb
Rails.application.routes.draw do
  post "sign_up", to: "users#create"
  get "sign_up", to: "users#new"

  post "log_in", to: "sessions#create"
  get "log_in", to: "sessions#new"

  delete "log_out", to: "sessions#destroy"

  resources :confirmations, only: %i(create edit new), param: :confirmation_token

  resources :stacks do
    resources :tasks, except: %i[ show ], shallow: true
  end
  root "stacks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/stack.rb
class Stack < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  enum status: [ :pending, :complete ]

  belongs_to :stack, counter_cache: true

  validates :description, presence: true

  scope :ordered, -> { order(id: :desc) }
end

app/models/user.rb
class User < ApplicationRecord
  CONFIRMATION_TOKEN_EXPIRATION = 10.minutes
  MAILER_FROM_EMAIL = "no-reply@turbo_fira.com"

  has_many :stacks, dependent: :destroy

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: URI::MailTo::EMAIL_REGEXP }

  before_save :downcase_email

  has_secure_password

  def confirm!
    update_columns(confirmed_at: Time.current)
  end

  def confirmed?
    confirmed_at.present?
  end

  def generate_confirmation_token
    signed_id(expires_in: CONFIRMATION_TOKEN_EXPIRATION, purpose: :confirm_email)
  end

  def send_confirmation_email!
    confirmation_token = generate_confirmation_token
    UserMailer.confirmation(self, confirmation_token).deliver_now
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :authenticate_user!
    before_action :current_user
    helper_method :current_user
  end

  def login(user)
    reset_session
    session[:user_id] = user.id
  end

  def logout
    reset_session
  end

  def redirect_if_authenticated!
    redirect_to root_path, notice: "You are already logged in." if current_user
  end

  def authenticate_user!
    redirect_to log_in_path, notice: "Log In or Sign Up to continue." unless current_user
  end

  private

  def current_user
    @_current_user ||= session[:user_id] && User.find(session[:user_id])
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
  def new
    @user = User.new
  end

  def edit
    @user = User.find_signed(params[:confirmation_token], purpose: :confirm_email)

    if @user.present?
      @user.confirm!
      redirect_to root_path, notice: "Your email has been confirmed."
    else
      redirect_to new_confirmation_path, notice: "Invalid token."
    end
  end

  def create
    @user = User.find_by(email: params[:user][:email].downcase)

    if @user.present? && !@user.confirmed?
      @user.send_confirmation_email!
      redirect_to root_path, notice: "Check your email for confirmation instructions."
    else
      redirect_to new_confirmation_path, notice: "We could not find a user with that email or that email has already been confirmed."
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_authenticated!, except: :destroy
  skip_before_action :authenticate_user!, except: :destroy

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])

    if @user && @user.authenticate(params[:user][:password])
      login(@user)

      redirect_to root_path, notice: "Logged in successfully!"
    else
      @user = User.new(email: params[:user][:email], password: params[:user][:password])
      @user.errors.add(:base, message: "Invalid email or password.")
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    logout
    redirect_to log_in_path, notice: "Logged out successfully."
  end
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  before_action :set_stack, only: %i[ show edit update destroy ]

  def index
    @stacks = current_user.stacks
  end

  def show
  end

  def new
    @stack = Stack.new
  end

  def edit
  end

  def create
    @stack = current_user.stacks.build(stack_params)

    if @stack.save
      redirect_to @stack, notice: "Stack was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @stack.update(stack_params)
      redirect_to @stack, notice: "Stack was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @stack.destroy
    redirect_to stacks_url, notice: "Stack was successfully destroyed.", status: :see_other
  end

  private

  def set_stack
    @stack = Stack.find(params[:id])
  end

  def stack_params
    params.require(:stack).permit(:title)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ edit update destroy ]
  before_action :set_stack, only: %i[ index create new ]

  def index
    @tasks = Task.where(stack: @stack).ordered
  end

  def new
  end

  def edit
  end

  def create
    @task = Task.new(task_params)
    @task.stack = @stack

    respond_to do |format|
      if @task.save
        format.turbo_stream
        format.html { redirect_to stack_tasks_path(@stack), notice: "Task was successfully created." }
      else
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@task)}_form", partial: "form", locals: { task: @task }) }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    if @task.update(task_params)
      respond_to do |format|
        format.turbo_stream { render turbo_stream: turbo_stream.replace("#{helpers.dom_id(@task)}_item", @task) }
        format.html { redirect_to stack_tasks_path(@task.stack), notice: "Task was successfully updated.", status: :see_other }
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove("#{helpers.dom_id(@task)}_item") }
      format.html { redirect_to stack_tasks_path(@task.stack), notice: "Task was successfully destroyed.", status: :see_other }
    end
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def set_stack
    @stack = Stack.find(params[:stack_id])
  end

  def task_params
    params.require(:task).permit(:description, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_authenticated!
  skip_before_action :authenticate_user!

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_confirmation_email!
      login(@user)

      redirect_to root_path, notice: "Successfully registered!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def routes_namespacing(*args, actual_model)
    %w( create new index ).include?(action_name) ? args << actual_model : [actual_model]
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TurboFira</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>

    <% if notice.present? %>
      <div
        class="container mx-auto max-w-3xl relative px-4"
        id="flash"
        data-controller="flash"
      >
        <div class="absolute inset-0 pt-2 px-4">
          <div class="alert bg-base-100 border-0 shadow">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="stroke-info shrink-0 w-6 h-6"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
            <span><%= notice %></span>
            <button data-action="flash#close">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>
      </div>
    <% end %>

    <main class="container mx-auto max-w-3xl pt-24 px-4">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" class="alert alert-error flex mb-3">
    <svg xmlns="http://www.w3.org/2000/svg" class="self-start stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" /></svg>
    <div class="flex flex-col">
      <span><%= pluralize(resource.errors.count, "error") %> prohibited this <%= resource.class.model_name.human.downcase %> from being saved:</span>
      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="container mx-auto max-w-3xl px-4 mt-3 mb-1">
  <div class="flex justify-end divide-x space-x-2">
    <% if current_user %>
      <div><%= link_to current_user.email, root_path, class: "btn btn-ghost" %></div>
      <div class="pl-2"><%= button_to "Log Out", log_out_path, method: :delete, class: "btn btn-ghost" %></div>
    <% else %>
      <div><%= link_to "Log In", log_in_path, class: "btn btn-ghost" %></div>
      <div class="pl-2"><%= link_to "Sign Up", sign_up_path, class: "btn btn-ghost" %></div>
    <% end %>
  </div>
</div>

app/views/stacks/_form.html.erb
<%= form_with(model: stack) do |form| %>
  <%= render "shared/error_messages", resource: stack %>

  <div class="my-5">
    <%= form.label :title, class: "sr-only" %>
    <%= form.text_field :title, placeholder: "Add stack title", class: "input input-bordered w-full" %>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary" %>
    <%= link_to "Back to stacks", stacks_path, class: "btn ml-2" %>
  </div>
<% end %>

app/views/stacks/_stack.html.erb
<div id="<%= dom_id stack %>" class="flex space-x-4 w-full">
  <div class="bg-neutral rounded-xl shadow w-4/5 p-3">
    <div class="h-full flex justify-between items-center">
      <%= link_to stack_tasks_path(stack) do %>
        <p class="text-2xl font-bold text-base-300 hover:scale-y-125 transition delay-50"><%= stack.title %></p>
      <% end %>

      <div class="flex">
        <%= link_to "Edit", edit_stack_path(stack), class: "btn px-6" %>
      </div>
    </div>
  </div>

  <div class="stats shadow w-1/5">
    <div class="stat flex items-center">
      <div class="stat-title">Tasks</div>
      <div class="stat-value"><%= stack.tasks.size %></div>
    </div>
  </div>
</div>

app/views/stacks/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing stack</h1>

  <%= render "form", stack: @stack %>

  <div class="flex sm:justify-end sm:-mt-12 mt-6">
    <%= button_to "Delete", stack_path(@stack), method: :delete, class: "btn btn-warning" %>
  </div>
</div>

app/views/stacks/index.html.erb
<div class="w-full">
  <div class="flex justify-between">
    <h1>Stacks</h1>
    <%= link_to "New stack", new_stack_path, class: "btn btn-primary mb-6" %>
  </div>

  <div id="stacks" class="flex flex-col space-y-4">
    <%= render @stacks %>
  </div>
</div>

app/views/stacks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1>New stack</h1>

  <%= render "form", stack: @stack %>
</div>

app/views/stacks/show.html.erb
<div class="w-full">
  <div class="mx-auto">
    <%= render @stack %>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: routes_namespacing(:stack, task), id: "#{dom_id(task)}_form") do |form| %>
  <%= render "shared/error_messages", resource: task %>

  <%= form.label :description, class: "sr-only" %>

  <div class="relative">
    <%= form.text_field :description, placeholder: "Add a new task", class: "input input-bordered w-full outline-none focus:outline-none focus:ring-0 focus:ring-cyan-950" %>

    <div class="absolute top-0 right-0">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<li id="<%= "#{dom_id(task)}_item" %>" class="py-3 mb-1">
  <%= turbo_frame_tag dom_id(task) do  %>
    <div class="flex items-center justify-between">
      <%= link_to task.description, edit_task_path(task), class: "flex-1 #{"line-through opacity-50" if task.complete?}" %>

      <div class="flex items-center space-x-3">
        <% if task.pending? %>
          <%= button_to "Mark complete", task_path(task, task: { status: "complete" }), method: :patch, class: "btn btn-sm" %>
        <% else %>
          <%= button_to "Mark pending", task_path(task, task: { status: "pending" }), method: :patch, class: "btn btn-success btn-sm" %>
        <% end %>

        <%= button_to "Delete", task_path(task), method: :delete, class: "btn btn-error btn-sm" %>
      </div>
    </div>
  <% end %>
</li>

app/views/tasks/create.turbo_stream.erb
<%= turbo_stream.prepend "tasks", @task %>

<%= turbo_stream.replace "#{dom_id(Task.new)}_form" do %>
  <% render "form", task: Task.new %>
<% end %>

app/views/tasks/edit.html.erb
<%= turbo_frame_tag dom_id(@task) do %>
  <%= render "form", task: @task %>
<% end %>

app/views/tasks/index.html.erb
<div class="w-full">
  <h1>Tasks</h1>

  <div class="mb-6">
    <%= render "form", task: Task.new %>
  </div>

  <ul id="tasks" class="divide-y list-none">
    <%= render @tasks %>
  </ul>
</div>

app/views/tasks/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New task</h1>

  <%= render "form", task: @task %>
</div>

app/views/users/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1>Sign Up</h1>

  <%= form_with model: @user, url: sign_up_path do |form| %>
    <%= render "shared/error_messages", resource: @user %>

    <div class="space-y-3">
      <div>
        <%= form.label :email, class: "label-text" %>
        <%= form.text_field :email, placeholder: "example@mail.com", required: true, class: "input input-bordered w-full" %>
      </div>

      <div>
        <%= form.label :password, class: "label-text" %>
        <%= form.text_field :password, required: true, class: "input input-bordered w-full" %>
      </div>

      <div>
        <%= form.label :password_confirmation, class: "label-text" %>
        <%= form.text_field :password_confirmation, required: true, class: "input input-bordered w-full" %>
      </div>

      <div>
        <%= form.submit "Sign Up", class: "btn btn-primary w-full" %>
      </div>
    </div>
  <% end %>

  <div class="mt-6">
    <p class="text-center">Does have account? <%= link_to "Log In", log_in_path, class: "link" %></p>
  </div>
</div>